### ISSUE TITLE
rpath_stanza does not take stanza in whatever order

### ISSUE THREAD

**Issue by Bhusson-imr** [NOAA-EDAB/Rpath#13]
Hello!
I'm working on building 8 models for norwegian fjords. Being more familiar with R than EwE software, and because i would like the procedure to be as automatic and reproducible as possible, i would like to build those using Rpath. My models are based on a previous EwE (Pedersen et al., 2018) where there are 3 stanza groups, each with two stanza, large and small, and the larger ones appear before the smaller in the groups order.
when running rpath_stanza, the biomasses, survival and other parameters are not calculated, althought the function does not output any error
When digging into the code i saw that everything seemed to be done so that the order of the stanza do not matter, but it does. 
For me it comes from lines 22-23 of the function when defining fist and second:
first <- stanzafile[StGroupNum == isp, First]
second <- stanzafile[StGroupNum == isp, Last]
There, if the larger/ older species are put first, then their month is the first to appear. In my case e.g., first = c( 36,0), second=c(400,35).
that poses a problem because in the following loop on ist, ist=1 represent the youngest stage and first[ist] represent the older stage.
indeed, when i inverted young and old stanza in the model, the function worked nicely. I guess it could be fixed with a first <- first[order(first)] or something similar.
Thanks for all your work on this package!
bérengère

**Comment by slucey** [comment]
Thank you  for flagging this.

**Comment by slucey** [comment]
Forgot to close this issue.  The code is now

```
for(isp in 1:Nsplit){
    #Put the stanzas in order for each split species
    stnum <- order(stanzafile[StGroupNum == isp, First])
```

So the code should handle the stanzas regardless of their order.
