### ISSUE TITLE
Reproducible example and Rsim

### ISSUE THREAD

**Issue by rosalieb** [NOAA-EDAB/Rpath#17]
Hello,
I am no longer able to reproduce the example included in the help file for Rpath. The issue seems to be with the stanzas computation.
<img width="557" alt="Screenshot 2020-11-27 at 11 42 17" src="https://user-images.githubusercontent.com/24991270/100470181-c521dd00-30a5-11eb-98cd-7718653992f2.png">

I have no problem running the code on my own data, but I often refer to the example data set for comparisons. 
Do you know where that may come from?
Thanks in advance! 
Best,
Rosalie Bruel

**Comment by slucey** [comment]
Same as this [issue](https://github.com/NOAA-EDAB/Rpath/issues/37)
