### ISSUE TITLE
Rsim is not working

### ISSUE THREAD

**Issue by rosalieb** [NOAA-EDAB/Rpath#18]
Hello,
I am no longer able to run Rsim (or rather, the code runs, but there is no impact on my data). 
Here is the code I use (the absolute values may not make sense, I was just trying something very extreme to see if that would make the model react):

`Rp1 <- rsim.scenario(REco, Rpath.params = REco.params.LC, years = 1:100)`
`Rp1.2 <- adjust.forcing(Rp1, "ForcedMort", group = "Mysids", sim.year = 10:80, bymonth = F, value = 3)`
`Rs1.1 <- rsim.run(Rp1.1)`

I am not able to check whether this is a problem on my end because the example data set is not working for me (see other issue I opened). I am opening another issue in case it is two very different problems. 

Thanks in advance for your help.
Best regards,
Rosalie Bruel

**Comment by slucey** [comment]
Rosalie,

I will be looking into both of these issues today.  Sorry for the inconvenience.  One thing I noticed with your code above:

`Rs1.1 <- rsim.run(Rp1.1)`

is trying to run a scenario `Rp1.1.` whereas your adjustments are made in a scenario `Rp1.2`.  Please let me know if there is still an issue when you run with scenario `Rp1.2`.

Sean

**Comment by rosalieb** [comment]
Hi Sean, 
Thanks for your reply - I just tried the code this morning and it worked! 
I did not re-download the package, so I cannot explain what I did wrong several days in a row last week (I tried trouble shooting on my own before creating an issue. The discrepancy between Rp1.1 and Rp1.2 was just a copy paste error when I tried to simplify my code).

However, some options are still not working. I understood that I could force the model with any of the forcings:
<img width="561" alt="image" src="https://user-images.githubusercontent.com/24991270/100634942-e7ae3300-32fd-11eb-96c0-bb053fe91679.png">

`"ForcedBio"`, for example, is still not working for me.

A related question, I couldn't find where to define prey vulnerability?

Thank you very much for your time and work on the R implementation.

Rosalie

**Comment by slucey** [comment]
Sorry for the delayed response again.  Those forcing functions should be working but I'll look into them.  As for setting vulnerabilities, you can do that using the `adjust.scenario` function.  The parameter is `VV`.  I realize now that is still somewhat confusing so I will be looking to update that to vulnerability in the near future.

**Comment by slucey** [comment]
Rosalie,

I wanted to check and see if you are still having issues.

Sean
