### ISSUE TITLE
Corals as mixotrophic organisms 

### ISSUE THREAD

**Issue by leomarameo7** [NOAA-EDAB/Rpath#2]
Hello everyone ! 

How can we define in "Type parameter setting",  organisms heterotrophs ?
In EwE, there's Respiration parameter, and it can be set between 0 and 1. 
Thanks

**Comment by slucey** [comment]
Leonardo,

You can specify a mixotroph based on the proportion of primary production
as its type.  For example an autotroph is 1 while a heterotroph is 0.  So
if your coral receives 40% of their energy from the sun their type is 0.4.
Please let me know how this works for you as this feature has not been
tested thoroughly.

Thanks,
Sean


Sean M. Lucey
Fisheries Biologist
Ecosystem Dynamics and Assessment Branch
U. S. Dept. of Commerce/NOAA/NMFS
Northeast Fisheries Science Center
166 Water Street, Woods Hole, MA 02543
508-495-2011 (voice)
508-495-2232 (fax)

**Comment by leomarameo7** [comment]
Thanks, Sean ! It works. I set values in "Type" as you state. Next, I check the "diet compostion" matrix, including only "0.6" consumption of zooplankton. It doesn't matter if the data coral's composition doesn't reach value 1.

**Comment by slucey** [comment]
Make sure that your DC equals 1.  The code adjusts the diet to reflect the proportion of primary production.  For example if you have a mixotroph that gets 60% of its energy from the sun and filters 40% zooplankton and 60% phytoplankton (a DC of 1) the code figures out that the group consumes 0.4 and multiples that by 0.4 and 0.6.  This gives a realized diet of 0.6 PP, 0.16 zooplankton, and 0.24 phytoplankton.

**Comment by leomarameo7** [comment]
Sorry, but I don't understand, Sean. In my case, Corals only eats 0.6 ( 60%) of zooplankton.The rest cames from the sun. How do you reflect this fact in the DC ?  They don't eat phytoplankton. So, in the diet matrix, I insert in the column "Corals", only 0.6, in the line of zooplankton. The Rpath balanced the model, without errors... 
It sounds strange because, in EwE , there's always a error message with DC has to be =1

**Comment by slucey** [comment]
Rpath has the same constraint that all DC's should equal one.  Rpath only gives errors if you run the rpath.check.params function.  

So in your case the proportion of diet of zooplankton in coral should be 1.  Rpath will know that coral is a mixotroph group because their type is 0.4 not 0.  Therefore it will multiply the DC by 1 - type (in your case (1 - 0.4) * 1 = 0.6).  Otherwise it is multiplying 0.6 by 0.6 effectively making the contribution of zooplankton to the diet of coral 0.36.

**Comment by leomarameo7** [comment]
Thank you, Sean. I got it ! 
Now, when I use the function "check.rpath.params", it returns: 
fleets is a fleet and should not have a biomass...set to NA 
fleets are fleets and should not have a BioAcc...set to NA 
fleets are fleets and should not have an Unassim...set to NA 

Do I have to set these parameters of fleets equal to 0 ? 
Does NAs allow for parameters ?

**Comment by slucey** [comment]
They should be set to NA not zero.  If you used rpath.create.params function they should have automatically been set to NA.  As this is a different issue than the title I'm going to close this issue.  If you have further issues please start a new one.

**Comment by leomarameo7** [comment]
Thanks , Sean. 
In the same issue, 
I did what you say, I set coral's DC = 1 (zooplankton prey) and coral type = 0.4. 
When I check check.rpath.params, there's this message: 
Corals sum, 1 is not 1...check DC or proportion of primary production

**Comment by slucey** [comment]
Let me look into it and get back to you.

**Comment by leomarameo7** [comment]
Ok, 
Moreover, when I set Corals' type = 0.9, and DC = 1 (zooplankton) , It gives me "unbalanced model" . Before , with type = 0.4 , model was balanced. This is not what we expect , if we set corals as 90% autotrophs, trophic impact on zooplankton has to decrease.

**Comment by slucey** [comment]
That is an error in my check.params function.  I wrote it to generically cover heterotrophs and autotrophs but didn't take into account mixotrophs.  I'll have to fix that code but the balancing is working as it should.

**Comment by slucey** [comment]
@leomarameo7 this is not what I would expect either and I am not able to recreate this using a test model.  Please send me your parameter object and I will take a look at it.

**Comment by slucey** [comment]
Mixotroph calculation has been fixed.  It should now calculate the correct M2 and TL for mixotrophes.
