### ISSUE TITLE
Vignette for ecosense

### ISSUE THREAD

**Issue by aw2113** [NOAA-EDAB/Rpath#26]
Provide instructions and example for ecosense.

**Comment by aw2113** [comment]
Added a data folder to sense_beta branch. This folder includes the example Rpath models from the manuscript (aggregated versions of Bering, Chukchi, and GOA; no stanzas). Also, broke ground on a vignette (R/ecosense_proto_vignette.R). Not in Rmarkdown yet.

**Comment by aw2113** [comment]
Uploaded a proto vignette (ecosense.Rmd) on the sense_beta branch. Still has a ways to go.

**Comment by slucey** [comment]
Same as [this issue](https://github.com/NOAA-EDAB/Rpath/issues/53)
