### ISSUE TITLE
Stanza code speed may be a 1-line fix

### ISSUE THREAD

**Issue by kaydin** [NOAA-EDAB/Rpath#27]
Ran a profile on the stanza code and it spent 3 orders of magnitude more time on this single line than any other.  Fixing this line may remove the need for any other speedups or C++ code.  Lines 382-384 of ecopath.R (rpath.stanzas):

      for(a in (first[ist] + 1):second[ist]){
        StGroup[age == a, Survive := StGroup[age == a - 1, Survive] * survive_L]
      }

A huge amount of that time is calling data table for the lookups.  So maybe first copying the data from the data table to vectors in a single vector operation, followed by the calculations, then copying it back in a single operation, would really speed things up?

**Comment by slucey** [comment]
I'm not sure how to turn it into a vector as it is a recursive function. However, I played around with the `shift` function within `data.table` and that seems to have cut the processing time in half.

```
microbenchmark(
      for(a in (first[ist] + 1):second[ist]){
        StGroup[age == a, Survive := StGroup[age == a - 1, Survive] * survive_L]
      },
      for(a in (first[ist] + 1):second[ist]){
        StGroup[age == a, Survive := shift(Survive) * survive_L]
      }, times = 1000)
```
![image](https://user-images.githubusercontent.com/5578254/126000642-24fc04ab-7e20-4342-bde4-32642ef1790f.png)

I'm going to test a bit more but this is promising!

**Comment by slucey** [comment]
Tested with a larger stanza and the results are the same (about twice as fast).

![image](https://user-images.githubusercontent.com/5578254/126166030-94113976-67a5-4bf9-81bd-473ca105e35c.png)

**Comment by kaydin** [comment]
This new code creates NAs throughout the age structure for our EBS model, so breaks right away.  Here's some code that pulls our stanza files directly from github - use to test before/after?

# Ecosystem file names
# If resetting from 2018 files, Octopi has an extra space in base file
  Ebase <- "https://raw.githubusercontent.com/kaydin/alaska_ecopath/main/EBS_ACLIM_72_BIO_base.csv"  
  Ediet <- "https://raw.githubusercontent.com/kaydin/alaska_ecopath/main/EBS_ACLIM_72_BIO_diet.csv"  
  Eped  <- "https://raw.githubusercontent.com/kaydin/alaska_ecopath/main/EBS_ACLIM_72_BIO_ped_2.csv"   
  Estz  <- "https://raw.githubusercontent.com/kaydin/alaska_ecopath/main/EBS_ACLIM_72_BIO_stanzas.csv"  
  Estg  <- "https://raw.githubusercontent.com/kaydin/alaska_ecopath/main/EBS_ACLIM_72_BIO_stanza_groups.csv" 

# Setup Base Ecopath and Base Rsim scenario
  unbal <- rpath.stanzas(read.rpath.params(Ebase, Ediet, Eped, Estg, Estz)) 
  bal <- rpath(unbal)

**Comment by slucey** [comment]
I believe that I isolated the issue.  Apparently the `shift` function doesn't work recursively the way I wanted it too.  It is still part of the solution however.  Running some microbenchmarking now.

**Comment by slucey** [comment]
Not quite as good as before but I guess when you aren't actually calculating anything it would be faster.  Still should see some marked improvement.
![image](https://user-images.githubusercontent.com/5578254/127420594-bcac03c9-e74a-4624-a47c-d9dfe611ab19.png)

**Comment by slucey** [comment]
I've pushed the fix.  This is a little faster (and actually gives results).  However, I think we can still greatly increase the speed using some C code.

**Comment by kaydin** [comment]
The code still had a huge amount of calls to data.table in that loop.  This method - unrolling a local vector and using the cumprod() function - seems to speed things up by ~97%.  

I've pushed this change.

> unbal1 <- rpath.stanzas(unbal_base)
> unbal2 <- rpath.stanzas.new(unbal_base)
>
> all.equal(unbal1$stanzas$StGroup[[1]]$Survive, unbal2$stanzas$StGroup[[1]]$Survive)
[1] TRUE
> 
> all.equal(unbal1$stanzas$StGroup[[2]]$B,unbal2$stanzas$StGroup[[2]]$B)
[1] TRUE
> 
> all.equal(unbal1$stanzas$StGroup[[3]]$Q,unbal2$stanzas$StGroup[[3]]$Q)
[1] TRUE

> microbenchmark(rpath.stanzas(unbal_base), rpath.stanzas.new(unbal_base),times=10)
Unit: milliseconds
                             expr        min         lq       mean    median         uq        max neval
       rpath.stanzas(unbal_base) 16870.1371 17149.0903 17359.5837 17334.081 17544.8584 17766.7105    10
rpath.stanzas.new(unbal_base)   575.5508   590.7077   596.1686   595.634   599.0534   630.4065    10
