### ISSUE TITLE
Adjust functions not working by month

### ISSUE THREAD

**Issue by slucey** [NOAA-EDAB/Rpath#38]
From Leonardo Capitani via email:

Within the adjust.fishing function, how can I modify values by month? I have a vector of values (e.g. x) by month. When I run these lines I same values for all the years.

adjust.fishing(REco.sim_minima,

               'ForcedEffort',
               group = 'Pesca_Consumo',
               sim.year = 2013:2020,
               sim.month = 1:12,
               value = x)

**Comment by slucey** [comment]
I tested this out and the values are indeed repeated by year but not month.

**Comment by slucey** [comment]
Replacement value was indexed off of the year rather than the month.   Also added functionality to vary the new values for every month rather than just repeat for every month.

**Comment by kaydin** [comment]
fix merged
