### ISSUE TITLE
Better labels for webplot()

### ISSUE THREAD

**Issue by okenk** [NOAA-EDAB/Rpath#43]
Hi-- thanks so much for this package, I love being able to do all of the modeling in R!

A coauthor did not like the food web plot that I produced using `Rpath::webplot()` because all of the overlapping text was hard to read.  I solved this by slightly amending the function so that instead of directly plotting everything, it just saves the set of points (this was already there) and set of line segments (this is what I added), and then plotted it in ggplot so I could take advantage of the ggrapel package.

Here is the original figure:
![foodweb](https://user-images.githubusercontent.com/205013/166344227-21829137-4d99-4153-84c7-56d7afe7fae5.png)

And the updated one:
![ggrepel_plot](https://user-images.githubusercontent.com/205013/166344508-57d47870-d98e-43b6-85ba-9fe2118cbaf8.png)

(Slightly different geometries because they have different random number seeds.)

It seems like this could be useful for future users. I was wondering if you'd be interested in incorporating it into the package or what the process is for contributing?

Thanks,
Kiva

**Comment by slucey** [comment]
This is great!  I love seeing an easier solution to my rudimentary code.  Please feel free to make a pull request that we can review and incorporate.

**Comment by slucey** [comment]
Pull request #44
