### ISSUE TITLE
Different results between old repo and new one

### ISSUE THREAD

**Issue by okenk** [NOAA-EDAB/Rpath#45]
I was previously using an Rpath package installation from the old repo, https://github.com/slucey/RpathDev. I recently reinstalled Rpath using the new repo, and a model that was previously balanced is no longer balanced (😱 ). I think it might have to do with how the stanzas are calculated? Has this changed?

**Comment by okenk** [comment]
I looked into this and think it was some commits about a year ago by @kaydin (maybe 8735a8383d888bced13247dcd60149bcc93d2185). I noticed the commit says it changed the leading stanza to the last stanza. Some of my "leading" stanzas that are informed by more data are the juvenile stanzas, not the adult ones. I would love my model to work again without having to use an outdated version!

**Comment by okenk** [comment]
I believe this same commit caused issue #37. It would be great to revert to the previous version of the code.

**Comment by kaydin** [comment]
Just to add, one of the previous issues was that the last age class was
truncating early in the original version, so it’s possible that in the
fixed version, if you’re calculating biomass of an older pool from a
younger one that your balance biomass may change.  I’m traveling now so I
apologize I can’t look further until next week.

**Comment by okenk** [comment]
I see, thanks for looking into this! I have an EE that went from 0.90 to 3.94 once the stanza code changed. My intuition is this seems like a very large change just for an age truncation adjustment, though I know sometimes small changes can have big impacts with these complicated models...

**Comment by okenk** [comment]
I see, thanks. Should the changes lead to large changes in the calculated quantities? I have an EE for a non-leading stanza that went from 0.90 to 3.94, which seems like a lot for just an age truncation issue. But I know these models are also complicated so can get surprising results sometimes...

**Comment by kaydin** [comment]
Yeah that definitely sounds like too much change to be explained by the age
truncation.  If you could send me your model files (to ***@***.***) I can
have a look when back in the office next week (I don’t have a good example
of a juvenile leading stanza model to test).

**Comment by slucey** [comment]
Linked to issue #37

**Comment by kaydin** [comment]
Hi Kiva,

I've only had a brief time to look at this in between traveling (will be out after today until 1-August).  Given your time schedule for submission, I've pushed a branch to the repo called 'stanza_rollback' that you can install from github, that simply rolls back that one piece to your preferred version.  PLEASE NOTE that this brings back the bug in the older age classes that will still need to be fixed, so the final version will produce different biomasses after I can merge the two fixes in August (but hopefully not very big differences comparatively).

Best,
Kerim

**Comment by slucey** [comment]
@kaydin we need to merge `stanza_rollback` into dev

**Comment by kaydin** [comment]
@slucey understood, but that would break any EBS examples and the fitting branch, as the rollback version is broken for the EBS and our fitting tests - high priority to resolve in a way that works for both.

**Comment by slucey** [comment]
@kaydin ok.  Let's get @rklasky on this issue and mark as our highest priority.  Maybe we can set up a meeting early next week to get him going.

**Comment by slucey** [comment]
@okenk we're trying to finally get this resolved.  Do you have a reproducible example we could use for testing?  Feel free to email me.

**Comment by okenk** [comment]
[Model](https://github.com/okenk/cwc/blob/main/Data/GroupInfo_data_deleted.csv), [diet](https://github.com/okenk/cwc/blob/main/Data/Diet.csv), [stanzas](https://github.com/okenk/cwc/blob/main/Data/stanzas.csv)

I think the issue is some of the leading stanzas are the juvenile group. It is an estuary model and the state sampling program more effectively captures juveniles of some species.

**Comment by slucey** [comment]
@okenk I'm missing a few parameters to build your model.  What did you use for your unassimilated biomass values?  Also, I need the first and last months for each stanza group.

**Comment by okenk** [comment]
I believe the unassimilated biomass was 0. The R script that runs the model is [here](https://github.com/okenk/cwc/blob/main/R/ecopath_inputs.R)-- hopefully that helps!

**Comment by okenk** [comment]
Unassimilated biomass was not zero!

**Comment by slucey** [comment]
Closed by pull request #70
